logging:
    level:
        tk.mybatis: DEBUG
        com.yonyou.microservice.gate.admin: DEBUG
spring:
    application:
        name: ops-notify
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: NON_NULL
    datasource:
        name: test
        url: ${db.yc_base.url}
        username: ${db.yc_base.username:root}
        password: ${db.yc_base.pwd:rcs}
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    rabbitmq: 
        host: ${mq.yc_base.host:10.180.4.221}
        port: ${mq.yc_base.port:5672}
        username: ${mq.yc_base.username:mqadmin}
        password: ${mq.yc_base.password:Pass1234}
mybatis:
    basepackage: com.yonyou.cloud.ops.notify.mapper
    xmlLocation: classpath:mapper/**/*.xml

server:
    port: ${ops.admin.port:8860}

eureka:
    instance:
        statusPageUrlPath: /info
        healthCheckUrlPath: /health
swagger:
    basepackage: com.yonyou.cloud.ops.notify
    service:
        name: ops-notify
        description: ops-notify
        developer: joy



